### ISSUE TITLE
Ganglion Board can't be searched but by solving BLE adpater issue

### ISSUE THREAD

**Issue by lauraqing** [alexcastillo/ganglion-ble#2]
Solved:

Using Ganglion Board, processing 3.3.6, a general BLE adapter: Device was not found. 

-Reinstalled BLE driver using Zadig. See a very detailed note as below,

http://docs.openbci.com/OpenBCI%20Software/01-OpenBCI_GUI#the-openbci-gui-running-the-openbci_gui-running-on-windows

**Comment by alexcastillo** [comment]
Not following, what's the issue?

**Comment by lauraqing** [comment]
Already fixed the problem. No need for answers.

2017-11-17 22:23 GMT-05:00 Alex Castillo <notifications@github.com>:
